name: Feature request
description: File a feature request
title: "[Feature request]: "
labels: ["enhancement"]
assignees:
  - vaporvee
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: idea
    attributes:
      label: What is your idea?
      description: Tell me what you want to see in the addon.
      placeholder: Tell me what you want to see!
      value: "I have a cool new feature!"
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: If you have anything else tell me here
      placeholder: Anything else.
    validations:
      required: false
